// Product data
const products = [
  {
    id: 1,
    name: "Terracotta Planter",
    sellerType: "artisan",
    artisanId: 1,
    artisan: "Asha",
    artisanVillage: "Kera Village",
    artisanStory: "I work with locally sourced red clay, using traditional firing methods passed down through generations. My designs are inspired by river forms and the textures of our land.",
    vendorAddress: null,
    price: 1200,
    description:
      "A hand-thrown terracotta planter made from locally sourced red clay. Fired using traditional techniques to achieve natural strength and earthy tones.",
    category: "Pottery",
    image: "https://via.placeholder.com/600x400",
    tags: ["Handmade", "Eco-friendly", "Clay"],
  },
  {
    id: 2,
    name: "Handloom Scarf",
    sellerType: "artisan",
    artisanId: 2,
    artisan: "Weaves of Mira",
    artisanVillage: "Mira Village",
    artisanStory: "Third generation weaver specializing in traditional patterns and natural dyes. Each piece tells a story of our heritage.",
    vendorAddress: null,
    price: 950,
    description:
      "A beautifully woven scarf using traditional handloom techniques and natural dyes. Made from pure cotton with intricate patterns.",
    category: "Handloom",
    image: "https://via.placeholder.com/600x400/EEE8DC/333333?text=Handloom+Scarf",
    tags: ["Handwoven", "Natural dyes", "Cotton"],
  },
  {
    id: 3,
    name: "Bamboo Basket",
    sellerType: "artisan",
    artisanId: 3,
    artisan: "Local cooperative",
    artisanVillage: "Green Valley",
    artisanStory: "Community of bamboo crafters working together to preserve traditional basket-making techniques.",
    vendorAddress: null,
    price: 650,
    description:
      "A sturdy bamboo basket handcrafted using traditional techniques. Perfect for storage or as a decorative piece.",
    category: "Bamboo",
    image: "https://via.placeholder.com/600x400/E8F5E9/333333?text=Bamboo+Basket",
    tags: ["Sustainable", "Handcrafted", "Natural"],
  },
  {
    id: 4,
    name: "Wooden Spoon Set",
    sellerType: "artisan",
    artisanId: 4,
    artisan: "Raju",
    artisanVillage: "Woodland Hills",
    artisanStory: "Woodworker specializing in kitchen utensils made from sustainable sources. Each piece is sanded and finished by hand.",
    vendorAddress: null,
    price: 420,
    description:
      "A set of 3 wooden spoons made from sustainable hardwood. Perfectly balanced for everyday cooking.",
    category: "Woodcraft",
    image: "https://via.placeholder.com/600x400/8B4513/FFFFFF?text=Wooden+Spoons",
    tags: ["Sustainable", "Kitchen", "Handcrafted"],
  },
  {
    id: 5,
    name: "Silver Jewelry Set",
    sellerType: "artisan",
    artisanId: 5,
    artisan: "Silver Crafts",
    artisanVillage: "Silver Town",
    artisanStory: "Family-run jewelry workshop specializing in traditional silverwork with modern designs.",
    vendorAddress: null,
    price: 2450,
    description:
      "A beautiful set of silver jewelry including earrings, necklace, and bracelet with traditional motifs.",
    category: "Jewelry",
    image: "https://via.placeholder.com/600x400/C0C0C0/333333?text=Silver+Jewelry",
    tags: ["Silver", "Traditional", "Elegant"],
  },
  {
    id: 6,
    name: "Natural Dye Set",
    sellerType: "artisan",
    artisanId: 6,
    artisan: "Natural Colors",
    artisanVillage: "Color Village",
    artisanStory: "Specialists in natural dyes using plants, roots, and flowers from our region.",
    vendorAddress: null,
    price: 850,
    description:
      "A complete set of natural dyes made from plants, roots, and flowers. Includes instructions for use.",
    category: "Natural dyes",
    image: "https://via.placeholder.com/600x400/FFB6C1/333333?text=Natural+Dyes",
    tags: ["Natural", "Eco-friendly", "DIY"],
  }
];

export default products;
